version: "3"

services:
  message-service:
    image: message-service:test1

  user-service:
    image: user-service:test1

    command:
      - "--mysql.address=192.168.11.162"

  user-edge-service:
    image: user-edge-service:test1
    links:
      - user-service
      - message-service
    command:
      - "--redis.address=192.168.11.162"

  course-service:
    image: course-service:test1
    links:
      - user-service
    command:
      - "--mysql.address=192.168.11.162"
      - "--zookeeper.address=192.168.11.162"
  course-edge-service:
    image: course-edge-service:test1
    links:
      - user-edge-service
    command:
      - "--zookeeper.address=192.168.11.162"

  api-gateway:
    image: api-gateway:test1
    links:
      - user-edge-service
      - course-edge-service
    ports:
      - 9090:9090